k3s_server_ip: '{{ hostvars[groups[''k3s_server''][0]].ansible_host | default(groups[''k3s_server''][0])
  }}'
k3s_server_host: '{{ groups[''k3s_server''][0] }}'
k3s_async_timeout: 1800
k3s_poll_interval: 10
